services:

  database:
    image: postgres:16
    restart: unless-stopped

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: cloud_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .

    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      database:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/cloud_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: tsoi-is-still-alive-very-secret-key-for-jwt-2024

volumes:
  postgres_data: